In [9]:
import pandas as pd 
import numpy as np

In [10]:
df = pd.read_csv("./Renewable_Energy.csv")
df.columns

Index(['ObjectId', 'Country', 'ISO2', 'ISO3', 'Indicator', 'Technology',
       'Energy_Type', 'Unit', 'Source', 'CTS_Name', 'CTS_Code',
       'CTS_Full_Descriptor', 'F2000', 'F2001', 'F2002', 'F2003', 'F2004',
       'F2005', 'F2006', 'F2007', 'F2008', 'F2009', 'F2010', 'F2011', 'F2012',
       'F2013', 'F2014', 'F2015', 'F2016', 'F2017', 'F2018', 'F2019', 'F2020',
       'F2021', 'F2022', 'F2023'],
      dtype='object')

In [11]:
import pandas as pd

# 假设你的 DataFrame 名为 df
# 1. 将年份列筛选出来
year_columns = [col for col in df.columns if col.startswith('F')]

# 2. 使用 pd.melt 将这些列转化为一列
df_melted = pd.melt(
    df,
    id_vars=[col for col in df.columns if col not in year_columns],  # 保留非年份的列
    value_vars=year_columns,  # 转换的年份列
    var_name='Year',  # 新列的名称
    value_name='Value'  # 对应的值列名称
)

# 3. 去掉 'F' 前缀（如果需要）
df_melted['Year'] = df_melted['Year'].str.lstrip('F')

# 查看结果
print(df_melted)

       ObjectId             Country ISO2   ISO3
0             1  Advanced Economies  NaN  AETMP  \
1             2  Advanced Economies  NaN  AETMP
2             3  Advanced Economies  NaN  AETMP
3             4  Advanced Economies  NaN  AETMP
4             5  Advanced Economies  NaN  AETMP
...         ...                 ...  ...    ...
49483      2058            Zimbabwe   ZW    ZWE
49484      2059            Zimbabwe   ZW    ZWE
49485      2060            Zimbabwe   ZW    ZWE
49486      2061            Zimbabwe   ZW    ZWE
49487      2062            Zimbabwe   ZW    ZWE

                            Indicator                         Technology
0              Electricity Generation                          Bioenergy  \
1      Electricity Installed Capacity                          Bioenergy
2              Electricity Generation                       Fossil fuels
3      Electricity Installed Capacity                       Fossil fuels
4              Electricity Generation  Hydropower (excl. Pumped Storage)
...                               ...                                ...
49483  Electricity Installed Capacity                       Fossil fuels
49484          Electricity Generation  Hydropower (excl. Pumped Storage)
49485  Electricity Installed Capacity  Hydropower (excl. Pumped Storage)
49486          Electricity Generation                       Solar energy
49487  Electricity Installed Capacity                       Solar energy

               Energy_Type                  Unit
0          Total Renewable  Gigawatt-hours (GWh)  \
1          Total Renewable         Megawatt (MW)
2      Total Non-Renewable  Gigawatt-hours (GWh)
3      Total Non-Renewable         Megawatt (MW)
4          Total Renewable  Gigawatt-hours (GWh)
...                    ...                   ...
49483  Total Non-Renewable         Megawatt (MW)
49484      Total Renewable  Gigawatt-hours (GWh)
49485      Total Renewable         Megawatt (MW)
49486      Total Renewable  Gigawatt-hours (GWh)
49487      Total Renewable         Megawatt (MW)

                                                  Source
0      International Renewable Energy Agency (IRENA) ...  \
1      International Renewable Energy Agency (IRENA) ...
2      International Renewable Energy Agency (IRENA) ...
3      International Renewable Energy Agency (IRENA) ...
4      International Renewable Energy Agency (IRENA) ...
...                                                  ...
49483  International Renewable Energy Agency (IRENA) ...
49484  International Renewable Energy Agency (IRENA) ...
49485  International Renewable Energy Agency (IRENA) ...
49486  International Renewable Energy Agency (IRENA) ...
49487  International Renewable Energy Agency (IRENA) ...

                             CTS_Name CTS_Code
0              Electricity Generation    ECNEG  \
1      Electricity Installed Capacity    ECNEC
2              Electricity Generation    ECNEG
3      Electricity Installed Capacity    ECNEC
4              Electricity Generation    ECNEG
...                               ...      ...
49483  Electricity Installed Capacity    ECNEC
49484          Electricity Generation    ECNEG
49485  Electricity Installed Capacity    ECNEC
49486          Electricity Generation    ECNEG
49487  Electricity Installed Capacity    ECNEC

                                     CTS_Full_Descriptor  Year        Value
0      Environment, Climate Change, Mitigation, Renew...  2000   109628.668
1      Environment, Climate Change, Mitigation, Renew...  2000    17606.311
2      Environment, Climate Change, Mitigation, Renew...  2000  5563047.840
3      Environment, Climate Change, Mitigation, Renew...  2000  1267681.571
4      Environment, Climate Change, Mitigation, Renew...  2000  1219908.376
...                                                  ...   ...          ...
49483  Environment, Climate Change, Mitigation, Renew...  2023     1850.750
49484  Environment, Climate Change, Mitigation, Renew...  2023          NaN
49485  Environment, Climate Change, Mitigation, Renew...  2023     1080.015
49486  Environment, Climate Change, Mitigation, Renew...  2023          NaN
49487  Environment, Climate Change, Mitigation, Renew...  2023       45.949

[49488 rows x 14 columns]

In [12]:
df_melted.head()

,ObjectId,Country,ISO2,ISO3,Indicator,Technology,Energy_Type,Unit,Source,CTS_Name,CTS_Code,CTS_Full_Descriptor,Year,Value
0,1,Advanced Economies,NaN,AETMP,Electricity Generation,Bioenergy,Total Renewable,Gigawatt-hours (GWh),International Renewable Energy Agency (IRENA) ...,Electricity Generation,ECNEG,"Environment, Climate Change, Mitigation, Renew...",2000,109628.668
1,2,Advanced Economies,NaN,AETMP,Electricity Installed Capacity,Bioenergy,Total Renewable,Megawatt (MW),International Renewable Energy Agency (IRENA) ...,Electricity Installed Capacity,ECNEC,"Environment, Climate Change, Mitigation, Renew...",2000,17606.311
2,3,Advanced Economies,NaN,AETMP,Electricity Generation,Fossil fuels,Total Non-Renewable,Gigawatt-hours (GWh),International Renewable Energy Agency (IRENA) ...,Electricity Generation,ECNEG,"Environment, Climate Change, Mitigation, Renew...",2000,5563047.840
3,4,Advanced Economies,NaN,AETMP,Electricity Installed Capacity,Fossil fuels,Total Non-Renewable,Megawatt (MW),International Renewable Energy Agency (IRENA) ...,Electricity Installed Capacity,ECNEC,"Environment, Climate Change, Mitigation, Renew...",2000,1267681.571
4,5,Advanced Economies,NaN,AETMP,Electricity Generation,Hydropower (excl. Pumped Storage),Total Renewable,Gigawatt-hours (GWh),International Renewable Energy Agency (IRENA) ...,Electricity Generation,ECNEG,"Environment, Climate Change, Mitigation, Renew...",2000,1219908.376

In [13]:
df_melted.to_csv("energy_choice_country.csv")